django_project/mysite/books/urls.py
from django.urls import path
from . import views

app_name = 'books'
urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail')
]

django_project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
]

django_project/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    #path('', views.name, name='name'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

django_project/mysite/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

django_project/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_project/mysite/polls/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='name', max_length=100)

django_project/mysite/books/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher
# Create your views here.

class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context

class BookList(ListView):
    model = Book

class AuthorList(ListView):
    model = Author

class PublisherList(ListView):
    model = Publisher

class BookDetail(DetailView):
    model = Book

class AuthorDetail(DetailView):
    model = Author

class PublisherDetail(DetailView):
    model = Publisher

django_project/mysite/mysite/views.py
from django.views.generic.base import TemplateView
from django.apps import apps
class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['app_list'] = ['polls', 'books']
        dictVerbose = {}
        for app in apps.get_app_configs():
            if 'site-packages' not in app.path:
                dictVerbose[app.label] = app.verbose_name
        context['verbose_dict'] = dictVerbose
        return context

django_project/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic import DetailView
from polls.models import Question, Choice
from django.urls import reverse
from django.http import HttpResponseRedirect
from polls.forms import NameForm
import logging

logger = logging.getLogger(__name__)
# Create your views here.

class IndexView(ListView):
    template_name = 'polls/index.html'
    model = Question

class DetailView(DetailView):
    template_name = 'polls/detail.html'
    model = Question

class ResultsView(DetailView):
    template_name = 'polls/results.html'
    model = Question

def vote(request, question_id):
    logger.debug(f"vote().question_id: {question_id}")
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoseNotExist):
        return render(request, 'polls/detail.html',{'question': question,
                                                    'error_message': "You didn't select a choice",})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))


def name(request):
    if request.method == 'POST':
        form = NameForm(request.POST)

        if form.is_valid():
            new_name = form.cleaned_data['name']
            return HttpResponseRedirect('')
    else:
        form = NameForm()
    return render(request, 'polls/name.html', {'form': form})

django_project/mysite/books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.name }}</h1>

    <ul>
        <li>{{object.salutation }}</li>
        <li>Email: {{object.email }}</li>
    </ul>
{% endblock content %}

django_project/mysite/books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href="{% url 'books:author_detail' author.id%}">{{ author.name }}</a> </li>
        {% endfor %}
    </ul>
{% endblock content %}

django_project/mysite/books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <br>
    <ul>
        <li>Authors:
            {% for author in object.authors.all %}
            {{ author }}
            {% if not forloop.last %},{% else %}{% endif %}
            {% endfor %}
        </li>
        <li>Publisher: {{object.publisher }}</li>
        <li>Publication date: {{object.publication_date }}</li>
    </ul>
{% endblock content %}

django_project/mysite/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id%}">{{ book.title }}</a> </li>
        {% endfor %}
    </ul>
{% endblock content %}

django_project/mysite/books/templates/books/index.html
{% extends "base_books.html" %}
{% block content %}
    <h1>Book Mgmt System</h1>
    <li><a href="book/">Book</a> </li>
    <li><a href="author/">Author</a> </li>
    <li><a href="publisher/">Publisher</a> </li>
{% endblock content %}

django_project/mysite/books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}
    <h1>{{ object.name }}</h1>

    <ul>
        <li>{{object.website }}</li>
        <li>Address: {{object.address }}</li>
    </ul>
{% endblock content %}

django_project/mysite/books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id%}">{{ publisher.name }}</a> </li>
        {% endfor %}
    </ul>
{% endblock content %}

django_project/mysite/polls/templates/polls/detail.html
{% extends "base_polls.html "%}
{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text}}</h1></legend>>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id}}">
            <label for="choice{{ forloop.counter}}">
                {{ choice.choice_text}}
            </label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
{% endblock content %}

django_project/mysite/polls/templates/polls/index.html
{% extends "base_polls.html "%}
{% block content %}
    <ul>
        {% for question in object_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

django_project/mysite/polls/templates/polls/name.html
<form action="{% url 'polls.name'%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="OK">
</form>

django_project/mysite/polls/templates/polls/results.html
{% extends "base_polls.html "%}
{% block content %}

<h1>{{ question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} - {{choice.votes}} vote{{choice.voteslpluralize}}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

django_project/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'admin/css/base.css'%}"/>
    <title>{% block title%}My Amazing Site{% endblock %}</title>
</head>
<body>
    <div id="sidebar">

        {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin">Admin</a></li>
        </ul>
        {% endblock %}
        <br>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

django_project/mysite/templates/base_books.html
{% extends "base.html" %}

<title>{% block title %}Books Application Site{% endblock %}</title>

{% block  sidebar %}
{{ block.super }}
<ul>
    <li><a href="/books/">Books_home</a></li>
</ul>
{% endblock %}

django_project/mysite/templates/base_polls.html
{% extends "base.html" %}

<title>{% block title %}Polls Application Site{% endblock %}</title>

{% block  sidebar %}
{{ block.super }}
<ul>
    <li><a href="/polls/">Polls_home</a></li>
</ul>
{% endblock %}

django_project/mysite/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>shkim Django Applications</h2>
    <ul>
        {% for key, value in verbose_dict.items %}
        {% with url_key=key|add:':index' %}
            <li><a href="{% url url_key %}">{{ value }}</a> </li>
        {% endwith %}
        {% endfor %}
    </ul>
{% endblock content %}